print_aws_vault_install_help() {
  echo "Help with installing aws-vault:" 
  echo "  Go here: https://github.com/99designs/aws-vault" 
  echo "" 
  echo "Install using either Homebrew or asdf:" 
  echo "" 
  echo "Homebrew (macOS/Linux):" 
  echo "  brew install --formula 99designs/aws-vault/aws-vault || brew install aws-vault" 
  echo "" 
  echo "asdf (ensure asdf is installed):" 
  echo "  asdf plugin add aws-vault https://github.com/karancode/asdf-aws-vault.git" 
  echo "  asdf install aws-vault latest" 
  echo "  asdf set -u aws-vault latest" 
  echo "" 
  echo "Then configure profiles in ~/.aws/config, e.g.:" 
  echo "  [profile myprofile]" 
  echo "  region = us-east-1" 
  echo "  mfa_serial = arn:aws:iam::123456789012:mfa/you" 
  echo "" 
  echo "Test it:" 
  echo "  aws-vault list" 
  echo "  aws-vault exec myprofile -- aws sts get-caller-identity" 
} 
